export enum StorageType {
  PUBLIC_ADDRESS_CREATOR = "public_address_creator",
  PUBLIC_ADDRESS_COLLECTOR = "public_address_collector",
  PUBLIC_ADDRESS_STORER = "public_address_storer",
  PRIVATE_KEY = "private_key",
  PRIVATE_KEY_CREATOR = "private_key_creator",
  PRIVATE_KEY_COLLECTOR = "private_key_collector",
  PRIVATE_KEY_STORER = "private_key_storer",
  ACCESS_TOKEN = "access_token",
  ACCESS_COLLECTOR_TOKEN = "ACCESS_COLLECTOR_TOKEN",
  ACCESS_STORER_TOKEN = "ACCESS_STORER_TOKEN",
  REFRESH_TOKEN = "refresh_token",
  IS_REGISTERED = "is_registered",
  IS_REGISTERED_COLLECTOR = "is_registered_collector",
  IS_REGISTERED_STORER = "is_registered_storer",
}
